# Generated by Django 5.1.4 on 2025-02-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='reviews',
            field=models.TextField(default='No reviews found.'),
            preserve_default=False,
        ),
    ]
