# Generated by Django 5.1.6 on 2025-02-11 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_reviews'),
        ('movies', '0002_review'),
    ]

    operations = [
    ]
