# Generated by Django 5.1.4 on 2025-02-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_reviews"),
        ("movies", "0002_review"),
    ]

    operations = []
