# Generated by Django 5.1.4 on 2025-02-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_merge_0002_movie_reviews_0002_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="reviews",
        ),
    ]
