# Generated by Django 5.1.5 on 2025-02-12 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_remove_movie_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="movie", name="duration", field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
