# Generated by Django 5.1.4 on 2025-02-09 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_remove_movie_reviews"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="movie",
        ),
        migrations.AddField(
            model_name="order",
            name="movies",
            field=models.ManyToManyField(to="movies.movie"),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
