# Generated by Django 5.1.5 on 2025-02-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order", name="price", field=models.FloatField(default=0.0),
        ),
    ]
